### ISSUE TITLE
"/composer.phar": stat /composer.phar: no such file or directory

### ISSUE THREAD

**Issue by romqin** [ubermuda/docker-composer#1]
```
docker@boot2docker:~$ alias composer="docker run -i -t -v \$PWD:/srv ubermuda/composer"
docker@boot2docker:~$ composer create-project symfony/framework-standard-edition test
FATA[0000] Error response from daemon: Cannot start container 9ca9708bdb1f82c00d14809955f1ed9c57e1d95e8216484c6bce3a96a62b0231: exec: "/composer.phar": stat /composer.phar: no such file or directory 
```

**Comment by cbeier** [comment]
There is currently an SSL problem when installing Composer:

    PHP Warning:  readfile(): SSL operation failed with code 1. OpenSSL Error messages:
    error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed in Command line code on line 1
    PHP Warning:  readfile(): Failed to enable crypto in Command line code on line 1
    PHP Warning:  readfile(https://getcomposer.org/installer): failed to open stream: operation failed in Command line code on line 1

Therefore composer.phar not exist.
